### ISSUE TITLE
Upstream data errors

### ISSUE THREAD

**Issue by martypdx** [wooorm/html-element-attributes#10]
I found what look like data errors, possibly in upstream data:
- [`ShadowRoot.delegatesFocus` ended up in template](https://github.com/wooorm/html-element-attributes/blob/main/index.js#L342). This is essentially a shadowroot instance method, not sure how it ended up here.
- [`isindex` and `prompt` are neither elements nor attributes](https://github.com/wooorm/html-element-attributes/blob/main/index.js#L230).

**Comment by wooorm** [comment]
Can you provide more info on why you think the `shadow*` stuff aren’t attributes on `template`?
If you look at the HTML spec, it does say that they are content attributes? https://html.spec.whatwg.org/multipage/scripting.html#the-template-element

I’m closing for now but would love to hear back from you!
