### ISSUE TITLE
Missing html element 'span'

### ISSUE THREAD

**Issue by alexanderhorner** [wooorm/html-element-attributes#11]

**Comment by wooorm** [comment]
Hey!
This package is about attributes, it’s not a list of all html/etc elements.
`span` has no particular extra attributes that are allowed, other than the global ones (see `*`).
See https://github.com/wooorm/html-tag-names if you want to check which tag names are known to html.

**Comment by alexanderhorner** [comment]
Ah okay, I didn't realize that, that makes sense.

Thanks for answering so quickly. Nice to see this is so actively maintained.
