### ISSUE TITLE
Deprecated attributes?

### ISSUE THREAD

**Issue by lazarljubenovic** [wooorm/html-element-attributes#5]
Is it possible to somehow know which attributes are deprecated? Maybe if not in this list, is there another list with HTML5-only things so I can do cross-referencing?

**Comment by wooorm** [comment]
Hmm, no. This is a list of stuff you could support. And support for deprecated stuff is often still what you want.

If you’d like just current attributes, you could fork the project, and remove the `html4` crawling [from the build script](https://github.com/wooorm/html-element-attributes/blob/752e002a416e19c79575c882ff838250c0c263bd/build.js#L29).
