### ISSUE TITLE
Authoring question

### ISSUE THREAD

**Issue by NullVoxPopuli** [wooorm/html-element-attributes#9]
As a language-server author, I'm considering using this library, 
however, the types of
```
 * @type {Record<string, Array<string>>}
```

are not specific enough.

if the index.js were ts (and generated a js + d.ts) we could `as const` the attribute lists to get TS-fine-grained attribute suggestions in language servers (wrapping TS, such as what Vue, Svelte, and Ember do).

However, I understand if a repo doesn't want to adopt TS, and we can have a manually maintained .d.ts file, but it would basically be a duplicate of the index.js.

**Comment by wooorm** [comment]
- `as const` can also be done in JSDoc
- I’m pretty sure TS already infers that file as `as const`, I am explicitly overwriting that with the explicit type
- whether to use an as-const or a record depends: In other projects, I use this project, and want to look strings up in this project. That is a type error if `as const` was used. That is why these are records and arrays
- I don’t think TS can do both.

**Comment by wooorm** [comment]
Closing as I’m not sure what to do. The types that are exposed are `Record<string, Array<string>>` so that arbitrary strings can be used to look into it. `as const`, or the default, prevent `string` lookup.
